Repository alefragnani/vscode-project-manager, pull requests merged in 2018-12, with the labels that each got.

#228 Update Variables Reference
  .vscode/launch.json
  .vscode/tasks.json
Labels: enhancement, internal

#231 Add refresh command to view title
  images/ico-refresh-dark.svg
  images/ico-refresh-light.svg
  package.json
  src/extension.ts
Labels: enhancement

#229 Add command to add an auto-detected project as a favorite
  package.json
  src/extension.ts
Labels: activity bar, enhancement

#204 support Portable Mode
  src/extension.ts
Labels: PR needs update, enhancement, portable mode
